#!/usr/bin/env python3
"""Generate rtl/machine/MacPPC7300_cudarom.sv, Cuda's firmware as a ROM.

    python verilator\\cudarom.py

Reads rtl/machine/cuda/341s0060.bin (Cuda 2.40, Apple part 341S0060, 4352
bytes at 0F00-1FFF of the 68HC05's space, as MAME's "cuda" set has it:
CRC32 0F5E7B4A, SHA-1 972b3778146d9787b18c3a9874d505cf606b3e15) and writes
the module MacPPC7300_cuda reads it through: one byte a clock, registered, from
an array an initial block fills. Quartus makes that a block RAM ROM (a case
statement, the boot ROM's pattern, became 4,372 ALUTs of logic), and needs
no file path at build time, nor does Verilator. The file is checked against
the CRC first, so a damaged copy cannot be built in.
"""

import os
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
BIN = os.path.join(ROOT, "rtl", "machine", "cuda", "341s0060.bin")
OUT = os.path.join(ROOT, "rtl", "machine", "MacPPC7300_cudarom.sv")
BASE = 0x0F00
CRC = 0x0F5E7B4A


def main():
    rom = open(BIN, "rb").read()
    if len(rom) != 0x1100 or zlib.crc32(rom) != CRC:
        print("%s is not Cuda 2.40 (341S0060): %d bytes, CRC %08X" % (BIN, len(rom), zlib.crc32(rom)))
        return 1
    lines = [
        "// Generated by verilator/cudarom.py from rtl/machine/cuda/341s0060.bin: do not edit.",
        "//",
        "// MacPPC7300 - Cuda's firmware: Apple's 341S0060, Cuda 2.40, as dumped in MAME's",
        "// \"cuda\" set (CRC32 0F5E7B4A), 4352 bytes at 0F00-1FFF of the 68HC05E1's",
        "// space. One byte a clock, registered (MacPPC7300_cuda reads it on every clock);",
        "// addr is the offset from 0F00.",
        "",
        "module MacPPC7300_cudarom",
        "(",
        "\tinput  logic        clk,",
        "\tinput  logic [12:0] addr,",
        "\toutput logic [7:0]  q",
        ");",
        "",
        "logic [7:0] fw [0:%d];" % (len(rom) - 1),
        "",
        "initial begin",
    ]
    for i, b in enumerate(rom):
        lines.append("\tfw[%d] = 8'h%02X;" % (i, b))
    lines += [
        "end",
        "",
        "always_ff @(posedge clk) q <= fw[addr];",
        "",
        "endmodule",
        "",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d bytes at %04X-%04X" % (OUT, len(rom), BASE, BASE + len(rom) - 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
